name: Test and Auto-Merge

on:
    pull_request:
        branches:
            - "main"

permissions:
    contents: write
    pull-requests: write

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run tests with pytest
              run: |
                  pytest

    auto-merge:
        needs: test
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == false # Only merge if not already merged

        steps:
            - name: Auto-merge PR
              uses: pascalgn/automerge-action@v0.16.3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  merge-method: squash
